# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitterformv2.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setObjectName("button_submit")
        self.gridLayout_2.addWidget(self.button_submit, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 3, 2, 1)
        self.button_open = QtWidgets.QPushButton(self.centralwidget)
        self.button_open.setObjectName("button_open")
        self.gridLayout_2.addWidget(self.button_open, 1, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.QLEConsumerKey = QtWidgets.QLineEdit(self.centralwidget)
        self.QLEConsumerKey.setObjectName("QLEConsumerKey")
        self.verticalLayout_3.addWidget(self.QLEConsumerKey)
        self.QLEConsumerSecret = QtWidgets.QLineEdit(self.centralwidget)
        self.QLEConsumerSecret.setObjectName("QLEConsumerSecret")
        self.verticalLayout_3.addWidget(self.QLEConsumerSecret)
        self.QLEAccessKey = QtWidgets.QLineEdit(self.centralwidget)
        self.QLEAccessKey.setObjectName("QLEAccessKey")
        self.verticalLayout_3.addWidget(self.QLEAccessKey)
        self.QLEAccessSecret = QtWidgets.QLineEdit(self.centralwidget)
        self.QLEAccessSecret.setObjectName("QLEAccessSecret")
        self.verticalLayout_3.addWidget(self.QLEAccessSecret)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Twitter Data Miner"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "Twitter Username(s):"))
        self.button_open.setText(_translate("MainWindow", "Open File"))
        self.label_3.setText(_translate("MainWindow", "Consumer Key"))
        self.label_4.setText(_translate("MainWindow", "Consumer Secret"))
        self.label_2.setText(_translate("MainWindow", "Access Key"))
        self.label_5.setText(_translate("MainWindow", "Access Secret"))
